### ISSUE TITLE
Templates Outdated?

### ISSUE THREAD

**Issue by peter-mghendi** [tryphotino/PhotinoSamples.VSCodeTemplates#6]
Hello there :wave:,

I'm just getting started with Photino - which is really great, and I was wondering why the templates default to .NET 6. Additionally, some of the UI dependencies seem to be out of date as well, e.g Angular 14 instead of 17. Is this some kind of compatibility issue or should they default to the latest versions?

Thanks.

**Comment by philippjbauer** [comment]
Hi @peter-mghendi,

there are no issues using .NET 8 with the latest Photino.NET 2.6.0!

You can use the framework and version of your choice (or none at all).

The templates will be updated soon, it's a manual process that takes a while to complete. There are a few things we are currently working on fixing before we go through that process.

 Hope that helps!

**Comment by peter-mghendi** [comment]
Thanks @philippjbauer!
